# --- Identity ---
edc.participant.id=consumer
edc.hostname=100.78.21.5

# --- Endpoints ---
edc.dsp.callback.address=http://100.78.21.5:29194/protocol

web.http.port=29191
web.http.path=/api

web.http.management.port=29193
web.http.management.path=/management
web.http.management.auth.key=password

web.http.protocol.port=29194
web.http.protocol.path=/protocol

web.http.public.port=29291
web.http.public.path=/public

web.http.control.port=29192
web.http.control.path=/control

edc.vault.hashicorp.url=http://127.0.0.1:8200
edc.vault.hashicorp.token=<root-token>
edc.vault.hashicorp.api.secret.path=/v1/secret
edc.vault.hashicorp.health.check.enabled=false

# PostgreSQL settings
edc.postgres.jdbc.url=jdbc:postgresql://127.0.0.1:5432/pocdb
edc.postgres.user=pocuser
edc.postgres.password=pocpass

# Example named datasource for JDBC data-plane (uncomment if your module supports it)
edc.datasource.consumer-pg-ds.jdbc.url=jdbc:postgresql://127.0.0.1:5432/pocdb
edc.datasource.consumer-pg-ds.jdbc.user=pocuser
edc.datasource.consumer-pg-ds.jdbc.password=pocpass
edc.datasource.consumer-pg-ds.jdbc.driver=org.postgresql.Driver