edc.participant.id=consumer
edc.hostname=consumer

edc.dsp.callback.address=http://<host-ip>:29194/protocol

web.http.port=29191
web.http.path=/api

web.http.management.port=29193
web.http.management.path=/management
web.http.management.auth.key=password

web.http.protocol.port=29194
web.http.protocol.path=/protocol

web.http.public.port=29291
web.http.public.path=/public

web.http.control.port=29192
web.http.control.path=/control

edc.vault.hashicorp.url=http://vault:8200
edc.vault.hashicorp.token=<root-token>
edc.vault.hashicorp.api.secret.path=/v1/secret
edc.vault.hashicorp.health.check.enabled=false