# Use a single console handler
handlers= java.util.logging.ConsoleHandler
.level = INFO

# EDC logs higher verbosity
org.eclipse.edc.level = FINE
org.eclipse.edc.handlers = java.util.logging.ConsoleHandler

# Console handler configuration
java.util.logging.ConsoleHandler.level = FINE
java.util.logging.ConsoleHandler.formatter = java.util.logging.SimpleFormatter
