edc.participant.id=provider
edc.hostname=100.93.225.17

edc.dsp.callback.address=http://100.93.225.17:19194/protocol

web.http.port=19191
web.http.path=/api

web.http.management.port=19193
web.http.management.path=/management
web.http.protocol.port=19194
web.http.protocol.path=/protocol
web.http.management.auth.key=password

web.http.public.port=19291
web.http.public.path=/public

web.http.control.port=19192
web.http.control.path=/control

edc.vault.hashicorp.url=http://127.0.0.1:8200
edc.vault.hashicorp.token=<root-token>
edc.vault.hashicorp.api.secret.path=/v1/secret
edc.vault.hashicorp.health.check.enabled=false

edc.blobstore.endpoint.template=http://100.93.225.17:10000/%s

edc.aws.access.key=accessKeyId
edc.aws.secret.access.key=secretAccessKey
edc.aws.endpoint.override=http://100.78.21.5:9000
edc.aws.region=us-east-1
edc.aws.s3.path-style-enabled=true
